[package]
name = "cpub"
version = "0.1.0"
authors = ["Alberto"]
edition = "2021"

[dependencies]
thiserror = "1.0"
anyhow = "1.0"
chrono = "0.4"
uuid = { version = "0.8", features = ["serde", "v4"] }
xml-rs = "0.8"
image = "0.24"
zip = "0.5"
clap = "3.0"