name: Rust

on:
  push:
    branches: [ "master"]
  pull_request:
    branches: [ "master" ]
    types: [ opened, reopened, closed, edited ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install ARM Compiler
      run: sudo apt install -y gcc-aarch64-linux-gnu binutils-aarch64-linux-gnu
    - name: Install ARM Target
      run: rustup target add aarch64-unknown-linux-gnu
    - name: Build arm64
      run: cargo build --release --target aarch64-unknown-linux-gnu
    - name: Build x64
      run: cargo build --release --target x86_64-unknown-linux-gnu
    - uses: actions/upload-artifact@v3
      with:
        name: cpub-linux-arm64
        path: target/aarch64-unknown-linux-gnu/release/cpub
    - uses: actions/upload-artifact@v3
      with:
        name: cpub-linux-x64
        path: target/x86_64-unknown-linux-gnu/release/cpub

  build_macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install ARM Target
      run: rustup target add aarch64-apple-darwin
    - name: Build arm64
      run: cargo build --release --target aarch64-apple-darwin
    - name: Build x64
      run: cargo build --release --target x86_64-apple-darwin
    - uses: actions/upload-artifact@v3
      with:
        name: cpub-macos-arm64
        path: target/aarch64-apple-darwin/release/cpub
    - uses: actions/upload-artifact@v3
      with:
        name: cpub-macos-x64
        path: target/x86_64-apple-darwin/release/cpub

  build_windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install ARM Target
      run: rustup target add aarch64-pc-windows-msvc
    - name: Build arm64
      run: cargo build --release --target aarch64-pc-windows-msvc
    - name: Build x64
      run: cargo build --release --target x86_64-pc-windows-msvc
    - uses: actions/upload-artifact@v3
      with:
        name: cpub-windows-arm64
        path: target/aarch64-pc-windows-msvc/release/cpub.exe
    - uses: actions/upload-artifact@v3
      with:
        name: cpub-windows-x64
        path: target/x86_64-pc-windows-msvc/release/cpub.exe

  release:
    needs: [ build_linux, build_macos, build_windows ]
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          path: artifacts
      - name: Set exec permission
        run: chmod -R 755 artifacts
      - name: Generate archives
        run: |
          zip -j artifacts/cpub-macos-arm64.zip artifacts/cpub-macos-arm64/cpub
          zip -j artifacts/cpub-macos-x64.zip artifacts/cpub-macos-x64/cpub
          zip -j artifacts/cpub-linux-arm64.zip artifacts/cpub-linux-arm64/cpub
          zip -j artifacts/cpub-linux-x64.zip artifacts/cpub-linux-x64/cpub
          zip -j artifacts/cpub-windows-arm64.zip artifacts/cpub-windows-arm64/cpub
          zip -j artifacts/cpub-windows-x64.zip artifacts/cpub-windows-x64/cpub
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            artifacts/cpub-macos-arm64.zip
            artifacts/cpub-macos-x64.zip
            artifacts/cpub-linux-arm64.zip
            artifacts/cpub-linux-x64.zip
            artifacts/cpub-windows-arm64.zip
            artifacts/cpub-windows-x64.zip

